const express = require('express')
require('express-async-errors')
const app = express()
const cors = require('cors')
const config = require('./utils/config')
const {info, error} = require('./utils/logger')
const blogRouter = require('./controllers/blogs')
const userRouter= require('./controllers/users')
const mongoose =require('mongoose')
const middleware = require('./utils/middleware')
mongoose.set('strictQuery',false)
mongoose.connect(config.MONGODB_URI).then(result =>{
    info('connected to MongoDB')
})
.catch(e =>{
    error('error connected to MongoDB',e.message)
})
app.use(cors())
app.use(express.json())
app.use(middleware.requestLogger)
app.use('/api/users',userRouter)
app.use('/api/blogs',blogRouter)
app.use(middleware.unknownEndpoint)
app.use(middleware.errorHandler)
module.exports = app
